services:
  db:
    container_name: db_container
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  telegram_bot:
    container_name: telegram_bot_container
    image: telegram_bot_image
    build: .
    volumes:
      - ./files:/~/mdlp_overdue_test_task/files
    environment:
      - BOT_TOKEN=YOUR_TOKEN
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "443:443"
    links:
      - db:db
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  files:
